name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check code formatting
      run: cargo fmt --check

  clippy-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy (no_std)
      run: cargo clippy --verbose
    - name: Clippy (no_std + borsh)
      run: cargo clippy --verbose --no-default-features

  clippy-with-tests-and-benches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy (with tests)
      run: cargo clippy --verbose --tests
    - name: Clippy (with tests + borsh)
      run: cargo clippy --verbose --tests --benches --features borsh

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --features borsh

  test-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --no-default-features

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate docs
      run: cargo doc --verbose --features borsh
